language: python
python:
- '3.5'
addons:
  apt:
    packages:
    - enchant
install:
- pip install -e .
- pip install -r tests/requirements.txt
script:
- flake8 --ignore=E501,F401 ./
deploy:
  provider: pypi
  user: rustybower
  password:
    secure: ybpoJ3a+HbF0BTG4Nq7bTYKjCQiXcWYSfbA87Oih5LR6zkY8ZHki6uUBQNx6UpjpvEDRKDbaZEi4CSGZ549poQw97H5Cc6jy8ZwuEy/l/DB+igIjEco8zrT8OKhznf2nA4jmZRcAOn9SRWmaBBPezQLu9A8JegD6QqaOE8cHR2ZJJ/js7rCt5N6EFenGoma7Lv8vBuy1I9u0P3TE3mN2FJxIDStQH0qEllPos0fMi5tGOtHFyl2qq1QrXIrfNESLL9WvTnJ3vNXI+PaWquacdExrSbYq/bKvRFS6IzeqD09KzDVVKtBTSRFIK/JT3kIubqxB2FHISyTx/LdK+qeTwSLAM22XfnDPSQ1pcljH/14nu2oXRwE5CHn+Rd9ZmCPhleZUqSuTtCr062U0okIySqAMrRLuLTCAcRheN4ZbrfIzekn4l2292Pqa1KkwkKkrJCHBRnERQf1Ks3zCJIyG1ii16W36suVtxU2d4rowY/h0oy+FgeXxgHK06IfYp3ZGSWYYyssUANnTATu/8X9LXf4vjCuTqSDvbuRftvsPb7KkBAKC3xs5j5ji2T7YcA7fCIPrEdsvkICcTepPBOoYhf+McskyEWrYkPGLFubnACyMywV5NSX/ts40orO1nj8c6XPVv29QCCYbgSUMo+1WoNo+SDLxrtD/E3AZbru89kU=
  on:
    tags: true
    python: '3.5'
  skip_existing: true
